<?php

use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            ['London', 'london'],
            ['Birmingham', 'birmingham'],
            ['Liverpool', 'liverpool'],
            ['Nottingham', 'nottingham'],
            ['Sheffield', 'sheffield'],
            ['Bristol', 'bristol'],
            ['Glasgow', 'glasgow'],
            ['Leicester', 'leicester'],
            ['Edinburgh', 'edinburgh'],
            ['Leeds', 'leeds-3'],
            ['Cardiff', 'cardiff'],
            ['Manchester', 'manchester'],
            ['Stoke-on-Trent', 'stoke-on-trent'],
            ['Coventry', 'coventry'],
            ['Sunderland', 'sunderland-3'],
            ['Birkenhead', 'birkenhead'],
            ['Islington', 'islington'],
            ['Reading', 'reading'],
            ['Hull', 'hull'],
            ['Preston', 'preston-7'],
            ['Newport', 'newport-13'],
            ['Swansea', 'swansea'],
            ['Bradford', 'bradford-4'],
            ['Southend', 'southend-on-sea'],
            ['Belfast', 'belfast'],
            ['Derby', 'derby'],
            ['Plymouth', 'plymouth'],
            ['Luton', 'luton-3'],
            ['Wolverhampton', 'wolverhampton'],
            ['Westminster', 'city-of-westminster'],
            ['Southampton', 'southampton'],
            ['Blackpool', 'blackpool'],
            ['Milton Keynes', 'milton-keynes'],
            ['Bexley', 'bexley'],
            ['Northampton', 'northampton'],
            ['Archway', 'archway'],
            ['Norwich', 'norwich'],
            ['Dudley', 'dudley'],
            ['Aberdeen', 'aberdeen'],
            ['Portsmouth', 'portsmouth-5'],
            ['Newcastle', 'newcastle-upon-tyne'],
            ['Sutton', 'sutton-16'],
            ['Swindon', 'swindon-4'],
            ['Crawley', 'crawley-4'],
            ['Ipswich', 'ipswich'],
            ['Wigan', 'wigan'],
            ['Croydon', 'croydon-7'],
            ['Walsall', 'walsall'],
            ['Mansfield', 'mansfield'],
            ['Oxford', 'oxford'],
            ['Warrington', 'warrington-2'],
            ['Bournemouth', 'bournemouth'],
            ['Peterborough', 'peterborough'],
            ['Cambridge', 'cambridge-7'],
            ['Doncaster', 'doncaster'],
            ['York', 'york'],
            ['Poole', 'poole'],
            ['Gloucester', 'gloucester'],
            ['Burnley', 'burnley'],
            ['Huddersfield', 'huddersfield'],
            ['Telford', 'telford'],
            ['Dundee', 'dundee'],
            ['Blackburn', 'blackburn-5'],
            ['Basildon', 'basildon-2'],
            ['Middlesbrough', 'middlesbrough'],
            ['Bolton', 'bolton-5'],
            ['Stockport', 'stockport'],
            ['Brighton', 'brighton'],
            ['West Bromwich', 'west-bromwich'],
            ['Grimsby', 'grimsby'],
            ['Hastings', 'hastings'],
            ['High Wycombe', 'high-wycombe'],
            ['Watford', 'watford-5'],
            ['Saint Peters', 'saint-peters-4'],
            ['Burton upon Trent', 'burton-upon-trent'],
            ['Colchester', 'colchester'],
            ['Eastbourne', 'eastbourne'],
            ['Exeter', 'exeter'],
            ['Rotherham', 'rotherham'],
            ['Cheltenham', 'cheltenham'],
            ['Lincoln', 'lincoln'],
            ['Chesterfield', 'chesterfield'],
            ['Chelmsford', 'chelmsford'],
            ['Mendip', 'mendip'],
            ['Dagenham', 'dagenham'],
            ['Basingstoke', 'basingstoke'],
            ['Maidstone', 'maidstone'],
            ['Sutton Coldfield', 'sutton-coldfield'],
            ['Bedford', 'bedford'],
            ['Oldham', 'oldham'],
            ['Enfield', 'enfield'],
            ['Woking', 'woking'],
            ['St Helens', 'st-helens'],
            ['Worcester', 'worcester'],
            ['Gillingham', 'gillingham-2'],
            ['Becontree', 'becontree'],
            ['Worthing', 'worthing-4'],
            ['Rochdale', 'rochdale'],
            ['Solihull', 'solihull'],
            ['Leamington Spa', 'royal-leamington-spa'],
            ['Romford', 'romford'],
            ['Bath', 'bath'],
            ['Harlow', 'harlow'],
            ['Nuneaton', 'nuneaton'],
            ['High Peak', 'high-peak'],
            ['Darlington', 'darlington'],
            ['Southport', 'southport'],
            ['Chester', 'chester'],
            ['Stevenage', 'stevenage'],
            ['Wembley', 'wembley'],
            ['Grays', 'grays'],
            ['Harrogate', 'harrogate'],
            ['Hartlepool', 'hartlepool'],
            ['Londonderry County Borough', 'londonderry-county-borough'],
            ['Cannock', 'cannock'],
            ['Hemel Hempstead', 'hemel-hempstead'],
            ['St Albans', 'st-albans'],
            ['Redditch', 'redditch'],
            ['South Shields', 'south-shields'],
            ['Derry', 'derry'],
            ['Weston-super-Mare', 'weston-super-mare'],
            ['Halifax', 'halifax'],
            ['Beckenham', 'beckenham'],
            ['Tamworth', 'tamworth'],
            ['Scunthorpe', 'scunthorpe'],
            ['Stockton', 'stockton-on-tees'],
            ['Wakefield', 'wakefield'],
            ['Carlisle', 'carlisle'],
            ['Gateshead', 'gateshead'],
            ['Lisburn', 'lisburn'],
            ['Fylde', 'fylde'],
            ['Paisley', 'paisley'],
            ['Bracknell', 'bracknell'],
            ['Newcastle under Lyme', 'newcastle-under-lyme'],
            ['Battersea', 'battersea'],
            ['Crewe', 'crewe'],
            ['Chatham', 'chatham'],
            ['Hove', 'hove'],
            ['Aylesbury', 'aylesbury'],
            ['East Kilbride', 'east-kilbride'],
            ['Canary Wharf', 'canary-wharf'],
            ['Rugby', 'rugby'],
            ['Salford', 'salford-3'],
            ['Purley', 'purley'],
            ['Guildford', 'guildford'],
            ['Shrewsbury', 'shrewsbury'],
            ['Peckham', 'peckham'],
            ['Barnsley', 'barnsley-4'],
            ['Lowestoft', 'lowestoft'],
            ['Gosport', 'gosport'],
            ['Southall', 'southall'],
            ['Stafford', 'stafford'],
            ['Tunbridge Wells', 'royal-tunbridge-wells'],
            ['Ellesmere Port', 'ellesmere-port'],
            ['Rossendale', 'rossendale'],
            ['Folkestone', 'folkestone'],
            ['Brixton', 'brixton-4'],
            ['Wrexham', 'wrexham'],
            ['Torquay', 'torquay'],
            ['Maidenhead', 'maidenhead'],
            ['Kingswood', 'kingswood-7'],
            ['Taunton', 'taunton'],
            ['Waterlooville', 'waterlooville'],
            ['Macclesfield', 'macclesfield'],
            ['Bognor Regis', 'bognor-regis'],
            ['Newtownabbey', 'newtownabbey'],
            ['Kettering', 'kettering'],
            ['Buckley', 'buckley'],
            ['Great Yarmouth', 'great-yarmouth'],
            ['Runcorn', 'runcorn'],
            ['Ashford', 'ashford-6'],
            ['Tonypandy', 'tonypandy'],
            ['Scarborough', 'scarborough'],
            ['Widnes', 'widnes'],
            ['Aldershot', 'aldershot'],
            ['Bury', 'bury-5'],
            ['Barking', 'barking-3'],
            ['Castleford', 'castleford'],
            ['Hereford', 'hereford'],
            ['Bangor', 'bangor-9'],
            ['Stroud', 'stroud'],
            ['Margate', 'margate'],
            ['Chelsea', 'chelsea'],
            ['Loughborough', 'loughborough'],
            ['Welwyn Garden City', 'welwyn-garden-city'],
            ['Farnborough', 'farnborough-6'],
            ['Rhondda', 'rhondda'],
            ['Craigavon', 'craigavon'],
            ['Wallasey', 'wallasey'],
            ['Littlehampton', 'littlehampton'],
            ['Bridgend', 'bridgend-6'],
            ['Bootle', 'bootle-3'],
            ['Weymouth', 'weymouth'],
            ['Fareham', 'fareham'],
            ['Morley', 'morley-6'],
            ['Cheshunt', 'cheshunt'],
            ['Kidderminster', 'kidderminster'],
            ['Corby', 'corby'],
            ['Dartford', 'dartford'],
            ['Castlereagh', 'castlereagh'],
            ['Dewsbury', 'dewsbury'],
            ['Livingston', 'livingston'],
            ['Stourbridge', 'stourbridge'],
            ['Sale', 'sale'],
            ['Halesowen', 'halesowen'],
            ['Canterbury', 'canterbury'],
            ['South Croydon', 'south-croydon'],
            ['Huyton', 'huyton'],
            ['Barry', 'barry-9'],
            ['Gravesend', 'gravesend'],
            ['Eastleigh', 'eastleigh'],
            ['Acton', 'acton-7'],
            ['Washington', 'washington-8'],
            ['Braintree', 'braintree'],
            ['Hamilton', 'hamilton'],
            ['Brentwood', 'brentwood'],
            ['Esher', 'esher'],
            ['Crosby', 'crosby-5'],
            ['Reigate', 'reigate'],
            ['Dunstable', 'dunstable'],
            ['Morecambe', 'morecambe'],
            ['Cumbernauld', 'cumbernauld'],
            ['Redhill', 'redhill-4'],
            ['Horsham', 'horsham'],
            ['Staines', 'staines'],
            ['Batley', 'batley'],
            ['Wellingborough', 'wellingborough'],
            ['Clacton', 'clacton-on-sea'],
            ['Dunfermline', 'dunfermline'],
            ['Bletchley', 'bletchley'],
            ['Keighley', 'keighley'],
            ['Hayes', 'hayes-4'],
            ['Paignton', 'paignton'],
            ['Llanelli', 'llanelli'],
            ['Kirkcaldy', 'kirkcaldy'],
            ['Bromsgrove', 'bromsgrove'],
            ['Sittingbourne', 'sittingbourne'],
            ['South Benfleet', 'south-benfleet'],
            ['Banbury', 'banbury'],
            ['West Bridgford', 'west-bridgford'],
            ['Mitcham', 'mitcham'],
            ['Morden', 'morden-4'],
            ['Cwmbran', 'cwmbran'],
            ['Long Eaton', 'long-eaton'],
            ['Durham', 'durham'],
            ['Northwich', 'northwich'],
            ['Ayr', 'ayr'],
            ['Perth', 'perth'],
            ['Lancaster', 'lancaster'],
            ['Tipton', 'tipton'],
            ['Inverness', 'inverness'],
            ['Kilmarnock', 'kilmarnock'],
            ['Banstead', 'banstead'],
            ['Neath', 'neath'],
            ['King\'s Lynn', 'kings-lynn'],
            ['Winchester', 'winchester'],
            ['Barrow in Furness', 'barrow-in-furness'],
            ['Yeovil', 'yeovil'],
            ['Middleton', 'middleton-15'],
            ['Havant', 'havant'],
            ['Carshalton', 'carshalton'],
            ['Hinckley', 'hinckley'],
            ['Salisbury', 'salisbury'],
            ['Pontefract', 'pontefract'],
            ['Coatbridge', 'coatbridge'],
            ['Sutton in Ashfield', 'sutton-in-ashfield'],
            ['Grantham', 'grantham'],
            ['Merthyr Tydfil', 'merthyr-tydfil'],
            ['Great Sankey', 'great-sankey'],
            ['Greenock', 'greenock'],
            ['Ashton-under-Lyne', 'ashton-under-lyne'],
            ['Leigh', 'leigh-3'],
            ['Leatherhead', 'leatherhead'],
            ['Letchworth Garden City', 'letchworth-garden-city'],
            ['Newark', 'newark-on-trent'],
            ['Worksop', 'worksop'],
            ['Bury St Edmunds', 'bury-st-edmunds'],
            ['Kirkby', 'kirkby'],
            ['Wallsend', 'wallsend'],
            ['Redruth', 'redruth'],
            ['Welling', 'welling'],
            ['Christchurch', 'christchurch-3'],
            ['Andover', 'andover'],
            ['Stretford', 'stretford-2'],
            ['Dover', 'dover'],
            ['Hatfield', 'hatfield-5'],
            ['Altrincham', 'altrincham'],
            ['Coity', 'coity'],
            ['Newburn', 'newburn'],
            ['Boston', 'boston'],
            ['Holloway', 'holloway'],
            ['Lytham St Annes', 'lytham-st-annes'],
            ['Bridgwater', 'bridgwater'],
            ['Urmston', 'urmston'],
            ['Wokingham', 'wokingham'],
            ['Swadlincote', 'swadlincote'],
            ['Trowbridge', 'trowbridge'],
            ['Prescot', 'prescot'],
            ['Bexhill', 'bexhill-on-sea'],
            ['Bloxwich', 'bloxwich'],
            ['Ewell', 'ewell'],
            ['North Shields', 'north-shields'],
            ['Glenrothes', 'glenrothes'],
            ['Skelmersdale', 'skelmersdale'],
            ['Fleet', 'fleet-4'],
            ['Abingdon', 'abingdon'],
            ['Tonbridge', 'tonbridge'],
            ['Ramsgate', 'ramsgate'],
            ['Ilkeston', 'ilkeston'],
            ['Coalville', 'coalville'],
            ['Canvey Island', 'canvey-island'],
            ['Surbiton', 'surbiton'],
            ['Whitley Bay', 'whitley-bay'],
            ['Greenford', 'greenford'],
            ['Arnold', 'arnold'],
            ['Houghton-le-Spring', 'houghton-le-spring'],
            ['Bishops Stortford', 'bishops-stortford'],
            ['Leyland', 'leyland'],
            ['Rushden', 'rushden-2'],
            ['Leighton Buzzard', 'leighton-buzzard'],
            ['Yeadon', 'yeadon'],
            ['Blyth', 'blyth-4'],
            ['Eccles', 'eccles-4'],
            ['Redcar', 'redcar'],
            ['Airdrie', 'airdrie'],
            ['Peterlee', 'peterlee'],
            ['Farnham', 'farnham-7'],
            ['Chester-le-Street', 'chester-le-street'],
            ['Great Malvern', 'great-malvern'],
            ['Herne Bay', 'herne-bay'],
            ['Wilmslow', 'wilmslow'],
            ['Newton Abbot', 'newton-abbot'],
            ['Stirling', 'stirling'],
            ['Mangotsfield', 'mangotsfield'],
            ['Billericay', 'billericay'],
            ['Chipping Sodbury', 'chipping-sodbury'],
            ['Hitchin', 'hitchin'],
            ['Walkden', 'walkden'],
            ['Tyldesley', 'tyldesley'],
            ['Chippenham', 'chippenham-3'],
            ['Billingham', 'billingham'],
            ['Pontypool', 'pontypool'],
            ['Accrington', 'accrington'],
            ['Falkirk', 'falkirk'],
            ['Briton Ferry', 'briton-ferry'],
            ['Hoddesdon', 'hoddesdon'],
            ['Bridlington', 'bridlington'],
            ['Bentley', 'bentley-6'],
            ['Exmouth', 'exmouth'],
            ['Yate', 'yate'],
            ['Felling', 'felling'],
            ['Colwyn Bay', 'colwyn-bay'],
            ['Radcliffe', 'radcliffe'],
            ['Totton', 'totton'],
            ['Letchworth', 'letchworth'],
            ['Chorley', 'chorley'],
            ['Bicester', 'bicester'],
            ['Haywards Heath', 'haywards-heath'],
            ['Irvine', 'irvine'],
            ['Wigston Magna', 'wigston-magna'],
            ['Wednesfield', 'wednesfield'],
            ['Strood', 'strood'],
            ['Windsor', 'windsor-15'],
            ['Dumfries', 'dumfries'],
            ['Glossop', 'glossop'],
            ['Cramlington', 'cramlington'],
            ['Pudsey', 'pudsey'],
            ['Ebbw Vale', 'ebbw-vale'],
            ['Newbury', 'newbury'],
            ['Wickford', 'wickford'],
            ['Lichfield', 'lichfield'],
            ['Brighouse', 'brighouse'],
            ['Darwen', 'darwen'],
            ['Wisbech', 'wisbech'],
            ['Aston', 'aston-3'],
            ['Borehamwood', 'borehamwood'],
            ['Prestwich', 'prestwich'],
            ['Motherwell', 'motherwell'],
            ['Cleethorpes', 'cleethorpes'],
            ['Lower Earley', 'lower-earley'],
            ['Shirley', 'shirley-9'],
            ['Deeside', 'deeside'],
            ['Falmouth', 'falmouth'],
            ['Hyde', 'hyde'],
            ['Chichester', 'chichester'],
            ['Barnstaple', 'barnstaple'],
            ['Spalding', 'spalding'],
            ['Rutherglen', 'rutherglen'],
            ['Thornton-Cleveleys', 'thornton-cleveleys'],
            ['Aberdare', 'aberdare'],
            ['Caerphilly', 'caerphilly'],
            ['Ruislip', 'ruislip'],
            ['Saint Neots', 'saint-neots'],
            ['Burgess Hill', 'burgess-hill'],
            ['Beverley', 'beverley'],
            ['Deal', 'deal'],
            ['Wishaw', 'wishaw-2'],
            ['Pontypridd', 'pontypridd'],
            ['Winsford', 'winsford-2'],
            ['Harpenden', 'harpenden'],
            ['Rayleigh', 'rayleigh'],
            ['Whitstable', 'whitstable'],
            ['Camberley', 'camberley'],
            ['Barnet', 'barnet'],
            ['Bedworth', 'bedworth'],
            ['Heswall', 'heswall'],
            ['Hucknall', 'hucknall'],
            ['Egham', 'egham'],
            ['Sevenoaks', 'sevenoaks'],
            ['Kidsgrove', 'kidsgrove'],
            ['Newtownards', 'newtownards'],
            ['Didcot', 'didcot'],
            ['Nelson', 'nelson-8'],
            ['Burntwood', 'burntwood'],
            ['Carrickfergus', 'carrickfergus'],
            ['Felixstowe', 'felixstowe'],
            ['Kendal', 'kendal'],
            ['Consett', 'consett'],
            ['Witney', 'witney'],
            ['Ashton in Makerfield', 'ashton-in-makerfield'],
            ['Cheadle Hulme', 'cheadle-hulme'],
            ['Ballymena', 'ballymena'],
            ['Stanford-le-Hope', 'stanford-le-hope'],
            ['Bideford', 'bideford'],
            ['Rochester', 'rochester-5'],
            ['Shipley', 'shipley-2'],
            ['Heywood', 'heywood'],
            ['Brierley Hill', 'brierley-hill'],
            ['Stratford-upon-Avon', 'stratford-upon-avon'],
            ['Sunbury-on-Thames', 'sunbury-on-thames'],
            ['Newry', 'newry'],
            ['Ashington', 'ashington-2'],
            ['Cambuslang', 'cambuslang'],
            ['Kirkby in Ashfield', 'kirkby-in-ashfield'],
            ['Willenhall', 'willenhall'],
            ['Burngreave', 'burngreave'],
            ['Denton', 'denton-4'],
            ['Cleckheaton', 'cleckheaton'],
            ['Ashford', 'ashford-5'],
            ['Bearsden', 'bearsden'],
            ['Jarrow', 'jarrow'],
            ['Melton Mowbray', 'melton-mowbray'],
            ['Workington', 'workington'],
            ['Epsom', 'epsom'],
            ['Haverhill', 'haverhill'],
            ['Maghull', 'maghull'],
            ['Clydebank', 'clydebank'],
            ['Acocks Green', 'acocks-green'],
            ['East Grinstead', 'east-grinstead'],
            ['Flint', 'flint'],
            ['Westhoughton', 'westhoughton'],
            ['Frome', 'frome'],
            ['Congleton', 'congleton'],
            ['Camden Town', 'camden-town'],
            ['Ryde', 'ryde'],
            ['Bishop Auckland', 'bishop-auckland'],
            ['Northolt', 'northolt'],
            ['Newton Aycliffe', 'newton-aycliffe'],
            ['Rhyl', 'rhyl'],
            ['Hertford', 'hertford'],
            ['Staveley', 'staveley-4'],
            ['Coleraine', 'coleraine'],
            ['Farnworth', 'farnworth-2'],
            ['Crowthorne', 'crowthorne'],
            ['Hawarden', 'hawarden'],
            ['Bramhall', 'bramhall'],
            ['Coulsdon', 'coulsdon'],
            ['Bartley Green', 'bartley-green'],
            ['Hornchurch', 'hornchurch'],
            ['St Austell', 'st-austell'],
            ['Rhosllanerchrugog', 'rhosllanerchrugog'],
            ['Fleetwood', 'fleetwood'],
            ['Witham', 'witham'],
            ['Blackheath', 'blackheath-6'],
            ['Pitsea', 'pitsea'],
            ['Whitehaven', 'whitehaven'],
            ['Newport', 'newport-14'],
            ['Skegness', 'skegness'],
            ['Selby', 'selby'],
            ['Thetford', 'thetford'],
            ['Newton Mearns', 'newton-mearns'],
            ['Vale of Leven', 'vale-of-leven'],
            ['Wednesbury', 'wednesbury'],
            ['Feltham', 'feltham-2'],
            ['Thatcham', 'thatcham'],
            ['Hindley', 'hindley'],
            ['Plymstock', 'plymstock'],
            ['Ormskirk', 'ormskirk'],
            ['Warwick', 'warwick-7'],
            ['Rugeley', 'rugeley'],
            ['Golborne', 'golborne'],
            ['Gosforth', 'gosforth-3'],
            ['Huntingdon', 'huntingdon'],
            ['Daventry', 'daventry'],
            ['Droitwich', 'droitwich'],
            ['New Malden', 'new-malden'],
            ['New Milton', 'new-milton'],
            ['Ammanford', 'ammanford'],
            ['Portishead', 'portishead'],
            ['Droylsden', 'droylsden'],
            ['Arbroath', 'arbroath'],
            ['Musselburgh', 'musselburgh'],
            ['Evesham', 'evesham'],
            ['Whitefield', 'whitefield'],
            ['Lofthouse', 'lofthouse-3'],
            ['Penarth', 'penarth'],
            ['Bishopbriggs', 'bishopbriggs'],
            ['Belper', 'belper'],
            ['Formby', 'formby'],
            ['Burnham-on-Sea', 'burnham-on-sea'],
            ['Broadstairs', 'broadstairs'],
            ['Oadby', 'oadby-2'],
            ['Heanor', 'heanor'],
            ['Chapletown', 'chapletown'],
            ['Truro', 'truro'],
            ['Elgin', 'elgin'],
            ['Litherland', 'litherland'],
            ['Market Harborough', 'market-harborough'],
            ['Royton', 'royton'],
            ['Walton-on-Thames', 'walton-on-thames'],
            ['Wellington', 'wellington-9'],
            ['Woodford Green', 'woodford-green'],
            ['Stalybridge', 'stalybridge'],
            ['Godalming', 'godalming'],
            ['Potters Bar', 'potters-bar'],
            ['Seaford', 'seaford'],
            ['Alfreton', 'alfreton'],
            ['Camborne', 'camborne'],
            ['Kenilworth', 'kenilworth'],
            ['Seaham', 'seaham'],
            ['Thornaby', 'thornaby-on-tees'],
            ['Sudbury', 'sudbury-3'],
            ['Shetland', 'shetland'],
            ['Rawtenstall', 'rawtenstall'],
            ['Retford', 'retford'],
            ['Renfrew', 'renfrew'],
            ['Heavitree', 'heavitree'],
            ['Portadown', 'portadown'],
            ['Berkhamsted', 'berkhamsted'],
            ['Stanley', 'stanley-13'],
            ['Swanley', 'swanley'],
            ['Newton-le-Willows', 'newton-le-willows'],
            ['Rottingdean', 'rottingdean'],
            ['Amersham', 'amersham'],
            ['Hadley Wood', 'hadley-wood'],
            ['Ossett', 'ossett'],
            ['Maldon', 'maldon'],
            ['Buxton', 'buxton-5'],
            ['Horley', 'horley-3'],
            ['Cowes', 'cowes'],
            ['Dronfield', 'dronfield'],
            ['Ripley', 'ripley-5'],
            ['Bathgate', 'bathgate'],
            ['Omagh', 'omagh'],
            ['March', 'march'],
            ['Stowmarket', 'stowmarket'],
            ['Clevedon', 'clevedon'],
            ['Maesteg', 'maesteg'],
            ['Guiseley', 'guiseley'],
            ['Bordon', 'bordon'],
            ['Caterham', 'caterham'],
            ['Gainsborough', 'gainsborough-4'],
            ['Goole', 'goole'],
            ['Harwich', 'harwich'],
            ['East Dereham', 'east-dereham'],
            ['Bellshill', 'bellshill'],
            ['Chesham', 'chesham'],
            ['Gerrards Cross', 'gerrards-cross'],
            ['Crowborough', 'crowborough'],
            ['Stamford', 'stamford'],
            ['Stourport-on-Severn', 'stourport-on-severn'],
            ['Gorseinon', 'gorseinon'],
            ['Failsworth', 'failsworth'],
            ['Nailsea', 'nailsea'],
            ['Isleworth', 'isleworth'],
            ['Risca', 'risca'],
            ['Alloa', 'alloa'],
            ['Newmarket', 'newmarket-6'],
            ['Bingley', 'bingley'],
            ['Brownhills', 'brownhills'],
            ['Yateley', 'yateley'],
            ['Hythe', 'hythe-5'],
            ['Newquay', 'newquay'],
            ['Sandown', 'sandown'],
            ['Atherton', 'atherton'],
            ['Colne', 'colne-2'],
            ['Orkney', 'orkney'],
            ['Chandlers Ford', 'chandlers-ford-2'],
            ['Chalfont Saint Peter', 'chalfont-saint-peter'],
            ['Ampthill', 'ampthill'],
            ['Kempston Hardwick', 'kempston-hardwick'],
            ['Bowthorpe', 'bowthorpe'],
            ['Portslade', 'portslade'],
            ['Swinton', 'swinton-4'],
            ['Kingswinford', 'kingswinford'],
            ['Chislehurst', 'chislehurst'],
            ['Hailsham', 'hailsham'],
            ['Dumbarton', 'dumbarton'],
            ['Poulton le Fylde', 'poulton-le-fylde'],
            ['Brough', 'brough-4'],
            ['Leek', 'leek'],
            ['Kempston', 'kempston'],
            ['Penzance', 'penzance'],
            ['Dinnington', 'dinnington-3'],
            ['Faversham', 'faversham'],
            ['Tewkesbury', 'tewkesbury'],
            ['Antrim', 'antrim'],
            ['Kirkintilloch', 'kirkintilloch'],
            ['Earl Shilton', 'earl-shilton'],
            ['Tiverton', 'tiverton-4'],
            ['Adwick le Street', 'adwick-le-street'],
            ['Weybridge', 'weybridge'],
            ['South Ockendon', 'south-ockendon'],
            ['Irlam', 'irlam'],
            ['Chessington', 'chessington'],
            ['Melksham', 'melksham'],
            ['Horsforth', 'horsforth'],
            ['Clydach', 'clydach-3'],
            ['Dukinfield', 'dukinfield'],
            ['Great Wyrley', 'great-wyrley'],
            ['Yarm', 'yarm'],
            ['Shoreham', 'shoreham-by-sea'],
            ['Pinner', 'pinner'],
            ['Ely', 'ely-3'],
            ['Hook', 'hook-3'],
            ['South Elmsall', 'south-elmsall'],
            ['Hebburn', 'hebburn'],
            ['Mirfield', 'mirfield'],
            ['Emsworth', 'emsworth'],
            ['Aberystwyth', 'aberystwyth'],
            ['Oswestry', 'oswestry'],
            ['Prestatyn', 'prestatyn'],
            ['Horwich', 'horwich'],
            ['Lancing', 'lancing'],
            ['Rawmarsh', 'rawmarsh'],
            ['Eastwood', 'eastwood-6'],
            ['Peacehaven', 'peacehaven'],
            ['East Molesey', 'east-molesey'],
            ['West Molesey', 'west-molesey'],
            ['Southsea', 'southsea'],
            ['Wantage', 'wantage'],
            ['Isle of Lewis', 'isle-of-lewis'],
            ['Uckfield', 'uckfield'],
            ['Peterhead', 'peterhead'],
            ['Larne', 'larne'],
            ['Mansfield Woodhouse', 'mansfield-woodhouse'],
            ['Grove', 'grove-7'],
            ['Hadleigh', 'hadleigh-4'],
            ['Marlow', 'marlow'],
            ['Marple', 'marple'],
            ['Chapel Allerton', 'chapel-allerton-3'],
            ['Brymbo', 'brymbo'],
            ['Waltham Abbey', 'waltham-abbey'],
            ['Devizes', 'devizes'],
            ['Hampton', 'hampton-10'],
            ['Bangor', 'bangor-10'],
            ['Dalserf', 'dalserf'],
            ['Hedge End', 'hedge-end'],
            ['Sandbach', 'sandbach'],
            ['New Mills', 'new-mills'],
            ['Ascot', 'ascot'],
            ['Abergele', 'abergele'],
            ['Spennymoor', 'spennymoor'],
            ['Dorking', 'dorking'],
            ['Ramsbottom', 'ramsbottom'],
            ['Amersham', 'amersham-on-the-hill'],
            ['Moreton', 'moreton-3'],
            ['Biddulph', 'biddulph'],
            ['Bishopstoke', 'bishopstoke'],
            ['Ferndown', 'ferndown'],
            ['Barrhead', 'barrhead'],
            ['Bethnal Green', 'bethnal-green'],
            ['Ware', 'ware'],
            ['Maltby', 'maltby'],
            ['Bayswater', 'bayswater'],
            ['Warminster', 'warminster'],
            ['Teignmouth', 'teignmouth'],
            ['Walton-on-the-Naze', 'walton-on-the-naze'],
            ['Tynemouth', 'tynemouth'],
            ['Bushey', 'bushey'],
            ['Gelligaer', 'gelligaer'],
            ['Sleaford', 'sleaford'],
            ['Haydock', 'haydock'],
            ['Mountsorrel', 'mountsorrel'],
            ['Lewes', 'lewes'],
            ['Thorne', 'thorne'],
            ['Grangemouth', 'grangemouth'],
            ['Calne', 'calne'],
            ['Nantwich', 'nantwich'],
            ['Romsey', 'romsey'],
            ['Wath upon Dearne', 'wath-upon-dearne'],
            ['Cirencester', 'cirencester'],
            ['Blantyre', 'blantyre'],
            ['Westbury', 'westbury-6'],
            ['Guisborough', 'guisborough'],
            ['Bedlington', 'bedlington'],
            ['Frinton', 'frinton-on-sea'],
            ['Hayling Island', 'hayling-island'],
            ['Dorchester', 'dorchester-5'],
            ['Northallerton', 'northallerton'],
            ['Longfield', 'longfield'],
            ['Saint Andrews', 'saint-andrews'],
            ['Rochford', 'rochford'],
            ['High Blantyre', 'high-blantyre'],
            ['Cobham', 'cobham-3'],
            ['Brixham', 'brixham'],
            ['Whickham', 'whickham'],
            ['Alton', 'alton-6'],
            ['Biggleswade', 'biggleswade'],
            ['Harringay', 'harringay'],
            ['Cowley', 'cowley-6'],
            ['Lymington', 'lymington'],
            ['Kilwinning', 'kilwinning'],
            ['Louth', 'louth'],
            ['Johnstone', 'johnstone'],
            ['Carterton', 'carterton'],
            ['Ripon', 'ripon'],
            ['Bonnyrigg', 'bonnyrigg'],
            ['Hartley', 'hartley-6'],
            ['Banbridge', 'banbridge'],
            ['Chepstow', 'chepstow'],
            ['Penicuik', 'penicuik'],
            ['Ryton', 'ryton-4'],
            ['Viewpark', 'viewpark'],
            ['Aldridge', 'aldridge'],
            ['Longsight', 'longsight'],
            ['Basford', 'basford'],
            ['Kippax', 'kippax'],
            ['Conisbrough', 'conisbrough'],
            ['Carmarthen', 'carmarthen'],
            ['Hoyland Nether', 'hoyland-nether'],
            ['Tadley', 'tadley'],
            ['Kidlington', 'kidlington'],
            ['Royston', 'royston-5'],
            ['Bebington', 'bebington'],
            ['Swanscombe', 'swanscombe'],
            ['Baildon', 'baildon'],
            ['Porthcawl', 'porthcawl'],
            ['Hale', 'hale-8'],
            ['Keynsham', 'keynsham'],
            ['Elland', 'elland'],
            ['Saltash', 'saltash'],
            ['Earlsfield', 'earlsfield'],
            ['Erskine', 'erskine'],
            ['Wombwell', 'wombwell'],
            ['South Hayling', 'south-hayling'],
            ['Blackwood', 'blackwood-7'],
            ['Llandudno', 'llandudno'],
            ['Broxburn', 'broxburn'],
            ['Neston', 'neston-3'],
            ['Hale', 'hale-10'],
            ['Hazel Grove', 'hazel-grove'],
            ['Darton', 'darton'],
            ['Orpington', 'orpington'],
            ['Saffron Walden', 'saffron-walden'],
            ['Haslingden', 'haslingden'],
            ['Port Glasgow', 'port-glasgow'],
            ['Penrith', 'penrith'],
            ['Sinfin', 'sinfin'],
            ['Bredbury', 'bredbury'],
            ['Mexborough', 'mexborough'],
            ['Newport Pagnell', 'newport-pagnell'],
            ['Neston', 'neston-2'],
            ['Larkhall', 'larkhall-2'],
            ['Darras Hall', 'darras-hall'],
            ['Cleveleys', 'cleveleys'],
            ['Dursley', 'dursley'],
            ['Addlestone', 'addlestone'],
            ['Blaydon-on-Tyne', 'blaydon-on-tyne'],
            ['Petersfield', 'petersfield-3'],
            ['Matlock', 'matlock'],
            ['Brynmawr', 'brynmawr'],
            ['Bo\'ness', 'boness'],
            ['Corsham', 'corsham'],
            ['Wimborne Minster', 'wimborne-minster'],
            ['Tredegar', 'tredegar'],
            ['Bromborough', 'bromborough'],
            ['Garforth', 'garforth'],
            ['Hadley', 'hadley'],
            ['Ilkley', 'ilkley'],
            ['Armagh', 'armagh'],
            ['Clitheroe', 'clitheroe'],
            ['Prestwick', 'prestwick'],
            ['Knaresborough', 'knaresborough'],
            ['Troon', 'troon'],
            ['Thornton Heath', 'thornton-heath'],
            ['Otley', 'otley-2'],
            ['Abergavenny', 'abergavenny'],
            ['Skipton', 'skipton'],
            ['Bodmin', 'bodmin'],
            ['Ingleby Greenhow', 'ingleby-greenhow'],
            ['Haverfordwest', 'haverfordwest'],
            ['Clayton-le-Woods', 'clayton-le-woods'],
            ['Enniskillen', 'enniskillen'],
            ['Prenton', 'prenton'],
            ['Llantrisant', 'llantrisant-4'],
            ['Canford Heath', 'canford-heath'],
            ['Morpeth', 'morpeth'],
            ['Llantwit Major', 'llantwit-major'],
            ['Mildenhall', 'mildenhall-2'],
            ['Pinxton', 'pinxton'],
            ['Poynton', 'poynton'],
            ['Didsbury', 'didsbury'],
            ['West Wickham', 'west-wickham-3'],
            ['Stone', 'stone-4'],
            ['Bishops Cleeve', 'bishops-cleeve'],
            ['Strabane', 'strabane'],
            ['Featherstone', 'featherstone-3'],
            ['Hythe', 'hythe-4'],
            ['Fallowfield', 'fallowfield'],
            ['Ringwood', 'ringwood'],
            ['Hawick', 'hawick'],
            ['Ryhope', 'ryhope'],
            ['Dundonald', 'dundonald-5'],
            ['Forfar', 'forfar'],
            ['Bourne', 'bourne'],
            ['Hockley', 'hockley-4'],
            ['Beccles', 'beccles'],
            ['Littleborough', 'littleborough-2'],
            ['Knottingley', 'knottingley'],
            ['Beaconsfield', 'beaconsfield'],
            ['Bridport', 'bridport'],
            ['Helensburgh', 'helensburgh'],
            ['Burnage', 'burnage'],
            ['Pyle', 'pyle'],
            ['Rosyth', 'rosyth'],
            ['Haslemere', 'haslemere'],
            ['Middlewich', 'middlewich'],
            ['Milford Haven', 'milford-haven'],
            ['Market Deeping', 'market-deeping'],
            ['Kirk Sandall', 'kirk-sandall'],
            ['Wetherby', 'wetherby'],
            ['The Boldons', 'the-boldons'],
            ['Stoke Gifford', 'stoke-gifford'],
            ['Biggin Hill', 'biggin-hill'],
            ['Wombourn', 'wombourn'],
            ['Shepshed', 'shepshed'],
            ['Blacon', 'blacon'],
            ['Ashtead', 'ashtead'],
            ['Chafford Hundred', 'chafford-hundred'],
            ['Oxted', 'oxted'],
            ['Bargoed', 'bargoed'],
            ['Carluke', 'carluke'],
            ['Verwood', 'verwood'],
            ['Alsager', 'alsager'],
            ['Linlithgow', 'linlithgow'],
            ['Broxbourne', 'broxbourne'],
            ['Churchdown', 'churchdown'],
            ['Berwick', 'berwick-upon-tweed'],
            ['Streetly', 'streetly'],
            ['Bolton upon Dearne', 'bolton-upon-dearne'],
            ['Newhaven', 'newhaven'],
            ['Newhaven', 'newhaven-4'],
            ['Whitby', 'whitby'],
            ['Rustington', 'rustington'],
            ['Knutsford', 'knutsford'],
            ['Mayfield', 'mayfield'],
            ['Fraserburgh', 'fraserburgh'],
            ['Milngavie', 'milngavie'],
            ['Holywood', 'holywood-3'],
            ['Hetton le Hole', 'hetton-le-hole'],
            ['Uttoxeter', 'uttoxeter'],
            ['Driffield', 'driffield'],
            ['Chard', 'chard'],
            ['Stocksbridge', 'stocksbridge'],
            ['Milnrow', 'milnrow'],
            ['Bacup', 'bacup'],
            ['Brackley', 'brackley-4'],
            ['Chelmsley Wood', 'chelmsley-wood'],
            ['Abbey Wood', 'abbey-wood'],
            ['Broadfield', 'broadfield'],
            ['Flitwick', 'flitwick'],
            ['Limavady', 'limavady'],
            ['Cinderford', 'cinderford'],
            ['Street', 'street'],
            ['Armthorpe', 'armthorpe'],
            ['Buckingham', 'buckingham'],
            ['Nelson', 'nelson-9'],
            ['Cheetham Hill', 'cheetham-hill'],
            ['Smethwick', 'smethwick'],
            ['Saltcoats', 'saltcoats'],
            ['Longton', 'longton-3'],
            ['Inverurie', 'inverurie'],
            ['Whittlesey', 'whittlesey'],
            ['Newport', 'newport-10'],
            ['Frimley', 'frimley'],
            ['Hurstpierpoint', 'hurstpierpoint'],
            ['Dalkeith', 'dalkeith'],
            ['Eaton Socon', 'eaton-socon'],
            ['Portland', 'portland'],
            ['Galashiels', 'galashiels'],
            ['Bridgnorth', 'bridgnorth'],
            ['Sidmouth', 'sidmouth'],
            ['Mablethorpe', 'mablethorpe'],
            ['Hartshill', 'hartshill'],
            ['North Walsham', 'north-walsham'],
            ['Brixton Hill', 'brixton-hill'],
            ['Grange Hill', 'grange-hill'],
            ['Harold Wood', 'harold-wood'],
            ['Ashby de la Zouch', 'ashby-de-la-zouch'],
            ['Treharris', 'treharris'],
            ['Henlow', 'henlow'],
            ['Tavistock', 'tavistock'],
            ['Helston', 'helston'],
            ['West Drayton', 'west-drayton-3'],
            ['Prudhoe', 'prudhoe'],
            ['Giffnock', 'giffnock'],
            ['Elm Park', 'elm-park'],
            ['Rickmansworth', 'rickmansworth'],
            ['Purfleet', 'purfleet'],
            ['Minehead', 'minehead'],
            ['Sheerness', 'sheerness'],
            ['Dungannon', 'dungannon'],
            ['Tring', 'tring'],
            ['Chorleywood', 'chorleywood'],
            ['Kirkham', 'kirkham-4'],
            ['Halstead', 'halstead-2'],
            ['Cudworth', 'cudworth'],
            ['Haxby', 'haxby'],
            ['Barnham', 'barnham-4'],
            ['Montrose', 'montrose'],
            ['Ivybridge', 'ivybridge'],
            ['Tranent', 'tranent'],
            ['Catterick Garrison', 'catterick-garrison'],
            ['Market Drayton', 'market-drayton'],
            ['Armadale', 'armadale-5'],
            ['Bolsover', 'bolsover'],
            ['Cross Hills', 'cross-hills'],
            ['Tilbury', 'tilbury'],
            ['Charlton Kings', 'charlton-kings'],
            ['Blandford Forum', 'blandford-forum'],
            ['Todmorden', 'todmorden'],
            ['Thornbury', 'thornbury-6'],
            ['Wymondham', 'wymondham-2'],
            ['Codsall', 'codsall'],
            ['Sandy', 'sandy'],
            ['Liversedge', 'liversedge'],
            ['Lymm', 'lymm'],
            ['Westhill', 'westhill'],
            ['Belsize Park', 'belsize-park'],
            ['Bishopsworth', 'bishopsworth'],
            ['Heckmondwike', 'heckmondwike'],
            ['Syston', 'syston-3'],
            ['Henley on Thames', 'henley-on-thames'],
            ['Honiton', 'honiton'],
            ['Great Harwood', 'great-harwood'],
            ['Cowdenbeath', 'cowdenbeath'],
            ['Holyhead', 'holyhead'],
            ['Carnoustie', 'carnoustie'],
            ['Cheadle', 'cheadle-4'],
            ['Hexham', 'hexham'],
            ['Caldicot', 'caldicot'],
            ['Stonehaven', 'stonehaven'],
            ['Crumpsall', 'crumpsall'],
            ['Kingsteignton', 'kingsteignton'],
            ['Newtown', 'newtown-11'],
            ['Ulverston', 'ulverston'],
            ['Wells', 'wells'],
            ['Largs', 'largs'],
            ['Padiham', 'padiham'],
            ['Little Lever', 'little-lever'],
            ['Thame', 'thame'],
            ['Dawlish', 'dawlish'],
            ['Cheam', 'cheam'],
            ['Kimberley', 'kimberley-7'],
            ['Wootton Bassett', 'royal-wootton-bassett'],
            ['Atherstone', 'atherstone'],
            ['Mountain Ash', 'mountain-ash'],
            ['Woodbridge', 'woodbridge'],
            ['Ince-in-Makerfield', 'ince-in-makerfield'],
            ['Ilfracombe', 'ilfracombe'],
            ['Methil', 'methil'],
            ['Cranleigh', 'cranleigh'],
            ['Cookstown', 'cookstown'],
            ['Barton upon Humber', 'barton-upon-humber'],
            ['Featherstone', 'featherstone-2'],
            ['Timperley', 'timperley'],
            ['Kesgrave', 'kesgrave'],
            ['Belvedere', 'belvedere'],
            ['Great Bookham', 'great-bookham'],
            ['Penistone', 'penistone'],
            ['Abertillery', 'abertillery'],
            ['Codicote', 'codicote'],
            ['Leominster', 'leominster'],
            ['Ardrossan', 'ardrossan'],
            ['Oakham', 'oakham'],
            ['Beighton', 'beighton'],
            ['Shirebrook', 'shirebrook'],
            ['Downham Market', 'downham-market'],
            ['Oldbury', 'oldbury-5'],
            ['Knowle', 'knowle'],
            ['Shefford', 'shefford'],
            ['Pelsall', 'pelsall'],
            ['Slough', 'slough'],
            ['Immingham', 'immingham'],
            ['Brentford', 'brentford'],
            ['Buckhurst Hill', 'buckhurst-hill'],
            ['Diss', 'diss'],
            ['Desborough', 'desborough'],
            ['Harrow', 'harrow-on-the-hill'],
        ];

        DB::table('locations')->truncate();

        foreach ($locations as $location) {
            DB::table('locations')->insert([
                'name' => $location[0],
                'slug' => $location[1],
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ]);
        }
    }
}
